# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run test
            - apt-get update
                      - apt-get install -y protobuf-compiler
                      - >
                        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
                          sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
                          apt-get update && \
                          apt-get install -y google-chrome-stable xvfb procps
                      - npm install --unsafe-perm
                      - npm run test
                      - npm run e2e
